In [113]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
forest_fires = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv')
forest_fires['area']=np.log(pd.Series(forest_fires.area)+1)
forest_fires.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [114]:
forest_fires.isnull().sum()

X        0
Y        0
month    0
day      0
FFMC     0
DMC      0
DC       0
ISI      0
temp     0
RH       0
wind     0
rain     0
area     0
dtype: int64

In [115]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
MY_ENC = LabelEncoder()
MY_ENC.fit(forest_fires['month'])

LabelEncoder()

In [116]:
forest_fires['month']=MY_ENC.transform(forest_fires['month'])
forest_fires.head()

X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5      7  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4     10  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4     10  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6      7  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6      7  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [117]:
MY_ENC.fit(forest_fires['day'])
forest_fires['day']=MY_ENC.transform(forest_fires['day'])
forest_fires.head()

X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5      7    0  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4     10    5  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4     10    2  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6      7    0  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6      7    3  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [118]:
forest_fires['FFMC'] = forest_fires['FFMC'].astype(np.int64)
forest_fires['DMC'] = forest_fires['DMC'].astype(np.int64)
forest_fires['DC'] = forest_fires['DC'].astype(np.int64)
forest_fires['ISI'] = forest_fires['ISI'].astype(np.int64)
forest_fires['temp'] = forest_fires['temp'].astype(np.int64)
forest_fires['wind'] = forest_fires['wind'].astype(np.int64)
forest_fires['rain'] = forest_fires['rain'].astype(np.int64)
forest_fires['area'] = forest_fires['area'].astype(np.int64)
forest_fires.head()


X  Y  month  day  FFMC  DMC   DC  ISI  temp  RH  wind  rain  area
0  7  5      7    0    86   26   94    5     8  51     6     0     0
1  7  4     10    5    90   35  669    6    18  33     0     0     0
2  7  4     10    2    90   43  686    6    14  33     1     0     0
3  8  6      7    0    91   33   77    9     8  97     4     0     0
4  8  6      7    3    89   51  102    9    11  99     1     0     0

In [119]:
column_names_to_normalize = ['FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind', 'rain']
x = forest_fires[column_names_to_normalize].values
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
forest_fires_temp = pd.DataFrame(x_scaled, columns=column_names_to_normalize, index = forest_fires.index)
forest_fires[column_names_to_normalize] = forest_fires_temp
forest_fires.head()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


X  Y  month  day      FFMC       DMC        DC       ISI      temp  \
0  7  5      7    0  0.871795  0.086207  0.101993  0.089286  0.193548   
1  7  4     10    5  0.923077  0.117241  0.776084  0.107143  0.516129   
2  7  4     10    2  0.923077  0.144828  0.796014  0.107143  0.387097   
3  8  6      7    0  0.935897  0.110345  0.082063  0.160714  0.193548   
4  8  6      7    3  0.910256  0.172414  0.111372  0.160714  0.290323   

         RH      wind  rain  area  
0  0.423529  0.666667   0.0     0  
1  0.211765  0.000000   0.0     0  
2  0.211765  0.111111   0.0     0  
3  0.964706  0.444444   0.0     0  
4  0.988235  0.111111   0.0     0

In [0]:
data = forest_fires
target = data['area']

In [156]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data, target, train_size = 0.60)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


((310, 13), (207, 13), (310,), (207,))

In [157]:
############################################### My LinearRegression #################################
from sklearn.linear_model import LinearRegression
lr = LinearRegression ()
lr = lr.fit(X_train,Y_train)
predicted_lr = lr.predict(X_test)
from sklearn import metrics
mse = metrics.mean_squared_error(Y_test,predicted_lr)
mse

2.5030944502816724e-31

In [158]:
#################################### My Cross validation Linear Regression ####################################################
from sklearn.model_selection import cross_val_score  
all_accuracies = cross_val_score(estimator=lr, X=X_train, y=Y_train, cv=300)
all_accuracies.mean()

0.07

In [159]:
############################################ My Grid search linear Regression #######################################################
from sklearn.model_selection import GridSearchCV
param_grid = {'fit_intercept':[True,False], 'normalize':[True,False], 'copy_X':[True, False]};
reg = LinearRegression()
grid = GridSearchCV(lr, param_grid, cv = 5)
grid.fit(X_train, Y_train)
Y_pred_reg = grid.predict(X_test)
grid.best_params_

{'copy_X': True, 'fit_intercept': True, 'normalize': True}

In [160]:
############################################ My Decision tree#####################################################3
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc = dtc.fit(X_train, Y_train)
predicted_dtc = dtc.predict(X_test)
from sklearn import metrics
metrics.accuracy_score(Y_test, predicted_dtc)

1.0

In [136]:
####################################Cross validation Decision tree ####################################################
from sklearn.model_selection import cross_val_score  
all_accuracies = cross_val_score(estimator=dtc, X=X_train, y=Y_train, cv=190)
all_accuracies.mean()

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=190.
  % (min_groups, self.n_splits)), Warning)


0.9993421052631579

In [137]:
############################################Grid search#######################################################
from sklearn.model_selection import GridSearchCV
param_grid = {'max_depth':np.arange(2,200)}
grid = GridSearchCV(dtc, param_grid, cv=5, scoring='neg_mean_squared_error')
grid.fit(X_train, Y_train.values.ravel())
y_pred_class = grid.predict(X_test)
grid.best_params_

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'max_depth': 5}

In [138]:
###################################################KNN#############################################
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn =knn.fit(X_train, Y_train)
predicted_knn = knn.predict(X_test)
from sklearn import metrics
metrics.accuracy_score(Y_test, predicted_knn)

0.676923076923077

In [139]:
####################################Cross validation KNN ####################################################
from sklearn.model_selection import cross_val_score  
all_accuracies = cross_val_score(estimator=knn, X=X_train, y=Y_train, cv=5)
all_accuracies.mean()

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


0.6232932664254872

In [140]:
########################################### My Grid search KNN #######################################################
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors' :np.arange(1,10)}
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, param_grid, cv = 5)
grid.fit(X_train, Y_train)
predicted_knn = grid.predict(X_test)
grid.best_params_

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'n_neighbors': 1}

In [141]:
from skimage.filters import threshold_otsu

target = np.array(target)
threshold_global_otsu = threshold_otsu(target)
global_otsu = target >= threshold_global_otsu
global_otsu

array([False, False, False,  True,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True,  True,  True, False,  True,  True, False, False, False,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True, False, False,
       False,  True, False, False, False, False, False,  True, False,
        True, False,  True, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True,  True, False, False,  True, False, False, False,  True,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False,  True, False,  True,
       False, False, False, False, False,  True, False, False, False,
        True, False, False,  True, False,  True, False, False, False,
       False,  True,

In [142]:
print(threshold_global_otsu)
print(np.histogram(Y_test,np.unique(target)))
print(np.histogram(Y_pred_reg,np.unique(target)))
print(np.histogram(predicted_knn,np.unique(target)))
print(np.histogram(y_pred_class,np.unique(target)))

1
(array([73, 23, 18, 10,  4,  2]), array([0, 1, 2, 3, 4, 5, 6]))
(array([ 8, 17, 17, 10,  4,  1]), array([0, 1, 2, 3, 4, 5, 6]))
(array([79, 19, 21,  8,  2,  1]), array([0, 1, 2, 3, 4, 5, 6]))
(array([73, 23, 18, 10,  4,  2]), array([0, 1, 2, 3, 4, 5, 6]))


In [143]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_test, Y_pred_reg))
print(mean_squared_error(Y_test, predicted_knn))
print(mean_squared_error(Y_test, y_pred_class))

2.267762385246084e-30
0.35384615384615387
0.007692307692307693
